#pragma config(Motor,  port1,           frontRightMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port2,           backRightMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           frontLeftMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           backarmMotor,  tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           frontarmMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          backLeftMotor, tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings

// does NOT work needs debuging

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "VexTossUp.h"
#include "Vex_Competition_Includes.c"

void pre_auton(){
  bStopTasksBetweenModes = true;
}

task autonomous()
{
	foward (100);
  backwards(100);
  foward(2500);
  turn_right (900);
  foward (3000);
  backwards(2000);
  turn_left(1300);
  foward(1500);
  turn_right(1300);
  foward(2500);
  allOff();
}

task usercontrol()
{
	// User control code here, inside the loop
	while (true)
	{
	  motor[frontRightMotor] = vexRT[Ch3];
    motor[backRightMotor]  = vexRT[Ch3];

    motor[frontLeftMotor] = vexRT[Ch2];
    motor[backLeftMotor]  = vexRT[Ch2];

    if(vexRT[Btn6U] == 1){
      teleArmUp();
    }

    else if(vexRT[Btn6D] == 1){
			teleArmDown();
    }
    else{
    	teleArmOff();
    }
   // if(vexRT[Btn8U == 1]){
   // 	turn_right(1000);
   // }
  //  else{
   //		turn_right(0);
   // }


	}
}
