#pragma config(Motor,  port1,           frontRightMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port2,           backRightMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port4,           frontLeftMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           backarmMotor,  tmotorVex393, openLoop)
#pragma config(Motor,  port6,           frontarmMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port10,          backLeftMotor, tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)


#include "VexTossUp.h"        // has all funtions
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

task autonomous()
{
	foward (100);
  backwards(100);
  foward(2500);
  turn_left (900);
  foward (3000);
  backwards(2000);
  turn_right(1300);
  foward(1500);
  turn_right(1300);
  foward(2500);
  allOff();



}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		//drive
	  motor[frontRightMotor] = vexRT[Ch3];
    motor[backRightMotor]  = vexRT[Ch3];
    motor[frontLeftMotor] = vexRT[Ch2];
    motor[backLeftMotor]  = vexRT[Ch2];

    //arm
    if(vexRT[Btn6U] == 1){
      teleArmUp();
    }

    else if(vexRT[Btn6D] == 1){
    	teleArmDown();
    }
    else{
    	teleArmOff();
    }



	}
}
