#pragma config(Motor,  port1,           frontRightMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           backRightMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port4,           armMotor,      tmotorVex393, openLoop)
#pragma config(Motor,  port10,          backLeftMotor, tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "VexTossUp2.h"
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!



void pre_auton()
{
	bStopTasksBetweenModes = true;
}


int d = 2000;



task autonomous()
{

		armUp(1500);

	for(int j = 1; j <= 4; j++){
		foward(d);
		backwards(2000);
		wait1Msec (500);
		d=d+500;

	}

		allOff();
}

task usercontrol(){
	// User control code here, inside the loop

	while (true){
		int x = vexRT [Ch3];
		int y = vexRT [Ch2];


	motor[frontRightMotor] = y;
  motor[backRightMotor]  = y;
  motor[frontLeftMotor]  = x;
  motor[backLeftMotor]   = x;

      //arm
    if(vexRT[Btn6U] == 1){
      motor[armMotor] = 127;
      motor[armMotor] = 127;
    }

    else if(vexRT[Btn6D] == 1){
      motor[armMotor] = -50;
      motor[armMotor] = -50;
    }
    else{
    	motor[armMotor] = 0;
      motor[armMotor] = 0;
    }


	}
}
